apiVersion: v1
kind: Service
metadata:
  name: resnet18-inference-svc
spec:
  type: LoadBalancer
  selector:
    app: resnet18-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
